trigger:
- main   # runs on changes pushed to main branch

pool:
  vmImage: 'windows-latest'

steps:
- script: echo "Hello Azure Pipeline! Your setup works ðŸŽ‰"
  displayName: 'Run Hello World script'
